### ISSUE TITLE
Search Ingredients in Fridge

### ISSUE THREAD

**Issue by tclerico** [tclerico/iCook#20]
Done when:  a single ingredient can be searched for.

**Comment by colhay** [comment]
Spent 30 minutes. Added searchIngredient(String name) that searches the list of ingredients in the Fridge and attempts to match a name, ignoring case. If found it returns the Ingredient object,  else null.

**Comment by colhay** [comment]
This connects to #27

**Comment by colhay** [comment]
This connects to #20
