### ISSUE TITLE
Add tags to recipes

### ISSUE THREAD

**Issue by tclerico** [tclerico/iCook#40]
the recipe class needs a system for 'tags' that the recommendation system will use

**Comment by jackcutri** [comment]
done when: recipes include tags for dietary restrictions

**Comment by colhay** [comment]
Completed in 1.5 Hours. Added a private method tags to the Recipe class and wrote a getter method to get the tags, as well as a for loop in display() so that tags will be shown. Also wrote a new constructor test for recipes that are created with tags and a test for the tag getter method.
