### ISSUE TITLE
get ingredients from Fridge

### ISSUE THREAD

**Issue by colhay** [tclerico/iCook#6]
gets all the ingredients in a user's fridge.

**Comment by colhay** [comment]
#Reccomendations

**Comment by jackcutri** [comment]
Done when:  ingredient the user gets from the fridge will decrease by the amount they enter, given the ingredient is in the user's fridge, and the amount they entered is less than or equal to that in the fridge

**Comment by tclerico** [comment]
Done When: a given number of ingredients can be added to / removed from the fridge, all ingredients and their count can be displayed, and a single ingredient can be searched fro

**Comment by colhay** [comment]
Finished in 30 minutes. Created a method that returns the List of ingredients within a Fridge.
